### ISSUE TITLE
Магические значения

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#1]
https://github.com/kirillgenets/kekstagram/blob/0aeb9db14535b0cd72da3b7b2bc2f91c132cae27/js/main.js#L65
https://github.com/kirillgenets/kekstagram/blob/0aeb9db14535b0cd72da3b7b2bc2f91c132cae27/js/main.js#L90
https://github.com/kirillgenets/kekstagram/blob/0aeb9db14535b0cd72da3b7b2bc2f91c132cae27/js/main.js#L95

Не понятно, откуда берутся числа и что они означают. Нужно объявить их в качестве констант

**Comment by Morfey216** [comment]
https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L194

5 - магическое значение...

**Comment by Morfey216** [comment]
Константы следует объявлять в начале кода, т.е они должны следовать сразу после служебных инструкций...
https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L49-L53

**Comment by kirillgenets** [comment]
Исправил и переместил в начало
