### ISSUE TITLE
Действие по умолчанию

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#12]
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L221-L224

В таких случаях рекомендуют отменять действие по умолчанию. Это скорее перестраховка, но позволяет исключить случайности.
Пройдись по всему коду и поправь.

**Comment by kirillgenets** [comment]
прописал отмену действий по умолчанию во всех кейдаунах
