### ISSUE TITLE
Неиспользуемый параметр

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#13]
весьма странно всё написано:
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L179-L181

Зачем тебе параметр picture, если ты его не используешь?
В общем, с учетом https://github.com/kirillgenets/kekstagram/issues/10 - переписать этот код

**Comment by kirillgenets** [comment]
исправил (кажется...)

**Comment by Morfey216** [comment]
Это хорошо, что сомневаешься.
Да, формально ты это исправил, но фактически проблема осталась, поэтому проблему закрыть не могу.
Видимо, придется пояснить...
Вот твой код:
https://github.com/kirillgenets/kekstagram/blob/8675db28448da4bd0d5083c247167e6bcb7c63be/js/main.js#L185-L208
Давай разберемся, что здесь происходит...

```
postedPhotos.forEach(function (picture) {
   picturesFragment.appendChild(createPicture(postedPhotos.indexOf(picture)));
});
```
В параметр функции метода _forEach_ передается picture. Как ты думаешь, что это такое?
Правильный ответ - текущий объект массива _postedPhotos_ , т.е., другими словами, все данные о текущей картинке, верно? 
Чтобы проверить это, достаточно всего лишь вывести их в консоль, к примеру...
А что отыщет команда 
```
createPicture(postedPhotos.indexOf(picture))
плюс
postedPhotos[numberOfPicture] 
```
Правильно - те же самые данные!
Не верится? Давай сравним: 
Вот код: http://joxi.ru/bmo43ZzT3L6NY2
Вот консоль (фрагмент): http://joxi.ru/xAeqQzDHR1WJ9A

**Comment by kirillgenets** [comment]
ААААА, да лааадно!!! То есть я по сути и так имел все данные о картинке, потом, не зная этого, искал номер этой картинки и в функции createPicture брал эту картинку по номеру? Почему я раньше не додумался, что заставляю браузер делать лишнюю абсурдную работу...

**Comment by kirillgenets** [comment]
Поправил это, спасибо за подробное объяснение! Я бы сам даже не подумал, что вот так...

**Comment by Morfey216** [comment]
Всё, да не всё...
этот код 
https://github.com/kirillgenets/kekstagram/blob/e6f5b3b5074b8f20d3b3061d1881efb37b9896fc/js/main.js#L185-L187
лучше написать так:
```
      postedPhotos.forEach(function (picture, index) {
        picturesFragment.appendChild(createPicture(picture, index));
      });
```
а вот этот
https://github.com/kirillgenets/kekstagram/blob/e6f5b3b5074b8f20d3b3061d1881efb37b9896fc/js/main.js#L195-L210
перепишем таким образом:
```
      function createPicture(picture, index) {
        var pictureTemplateClone = pictureTemplate.cloneNode(true);
        // Заполнение картинки данными из объекта
        pictureTemplateClone.querySelector('.picture__img').src = picture.url; // Устанавливаем картинку
        pictureTemplateClone.querySelector('.picture__comments').textContent = picture.comments.length; // Устанавливаем количество комментариев
        pictureTemplateClone.querySelector('.picture__likes').textContent = picture.likes; // Устанавливаем количество лайков
        pictureTemplateClone.setAttribute('data-number', index);

        return pictureTemplateClone;
      }
```
Тогда и обработчики из https://github.com/kirillgenets/kekstagram/issues/14 перепишутся

**Comment by kirillgenets** [comment]
исправил

**Comment by Morfey216** [comment]
Не исправлено http://joxi.ru/823Pl1xT9yKoNA

**Comment by Morfey216** [comment]
теперь всё хорошо
