### ISSUE TITLE
Сложные условия

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#14]
Мне очень не нравится, как у тебя прописаны обработчики:
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L211-L227

Можно проще (если с умом):
http://joxi.ru/ZrJlP8YTwO7w32 - одна строчка кода...

С keydown будет чуть сложнее, но с учетом https://github.com/kirillgenets/kekstagram/issues/12 получим http://joxi.ru/D2P5PbYfqebqXA

Осталось разобраться с querySelector, но это уже твоя задача ))

**Comment by kirillgenets** [comment]
исправил. условие насчет className и вправду нелогичное, оно ведь по кейдауну в любом случае фокусится на  элементе picture

**Comment by kirillgenets** [comment]
querySelector в кейдауне здесь вообще не должен быть? нужно его убрать и придумать что-то другое?

**Comment by Morfey216** [comment]
Если есть  вот это
https://github.com/kirillgenets/kekstagram/issues/20

значит - что-то пошло "не так" )))

**Comment by kirillgenets** [comment]
ой, лучше вместо того, чтобы возиться с условиями, сделаю без делегирования, так же можно?

**Comment by kirillgenets** [comment]
исправил, теперь нет ошибки и сложных условий

**Comment by Morfey216** [comment]
Учитывая изменения в https://github.com/kirillgenets/kekstagram/issues/13#issuecomment-529123774
обработчики перепишем, сделав их работу универсальной и избавившись, наконец, от _querySelector_
```
      function initPicturesListeners(picture) {

        picture.addEventListener('click', onPictureClick);
        picture.addEventListener('keydown', onPictureKeyDown);

        function onPictureClick(evt) {
          drawBigPicture(getNumberOfPicture(evt.currentTarget));
        }

        function onPictureKeyDown(evt) {
          if (evt.key === 'Enter') {
            evt.preventDefault();
            drawBigPicture(getNumberOfPicture(evt.currentTarget));
          }
        }
      }
```

**Comment by kirillgenets** [comment]
надеюсь, что исправил
