### ISSUE TITLE
Нецелевое использование

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#15]
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L245-L247

В данном коде _picture_ - элемент DOM-дерева, из которого тебе нужен всего лишь один data-атрибут. Так может сразу его и передавать при вызове _drawBigPicture_?

**Comment by kirillgenets** [comment]
исправил
