### ISSUE TITLE
Еще один неиспользуемый параметр...

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#16]
Тебя ничего не смущает в этих двух строках?
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L255
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L328

**Comment by kirillgenets** [comment]
исправил
