### ISSUE TITLE
Ошибка именования обработчиков

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#19]
https://github.com/kirillgenets/kekstagram/blob/8675db28448da4bd0d5083c247167e6bcb7c63be/js/main.js#L336
https://github.com/kirillgenets/kekstagram/blob/8675db28448da4bd0d5083c247167e6bcb7c63be/js/main.js#L343
https://github.com/kirillgenets/kekstagram/blob/8675db28448da4bd0d5083c247167e6bcb7c63be/js/main.js#L402
https://github.com/kirillgenets/kekstagram/blob/8675db28448da4bd0d5083c247167e6bcb7c63be/js/main.js#L410
_Cancel_ и _cancelButton_ - разные вещи...

**Comment by kirillgenets** [comment]
исправил
