### ISSUE TITLE
Использование шаблонов

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#2]
Сразу много вопросов...
1. Сколько раз будет выполняться поиск #picture? А сколько нужно?
https://github.com/kirillgenets/kekstagram/blob/0aeb9db14535b0cd72da3b7b2bc2f91c132cae27/js/main.js#L126
2. Зачем здесь setAttribute?
https://github.com/kirillgenets/kekstagram/blob/0aeb9db14535b0cd72da3b7b2bc2f91c132cae27/js/main.js#L131
У img уже присутствует атрибут src, поэтому всё, что необходимо - прописать ссылку

И здесь тоже: https://github.com/kirillgenets/kekstagram/blob/f29da150f9df0c9aa593bac6212c4ab45c6ec981/js/main.js#L145

3. Более глобальный момент - я уже давал ссылку, повторю еще раз: https://learn.javascript.ru/modifying-document#klonirovanie-uzlov-clonenode
В данном случае правильнее один раз найти шаблон (см. пункт 1)  и клонировать его необходимое количество раз.

**Comment by Morfey216** [comment]
Так и не понял, для чего тебе понадобилось это, если у тебя уже есть фрагмент...
https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L128

Вместо
https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L46
используй
var pictureTemplate = document.querySelector('#picture').content.querySelector('.picture');
тогда строка 
https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L140
тебе даст сразу контент. Соответственно - строки 
https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L141-L147
можно переписать в виде:
pictureTemplateClone.querySelector('.picture__img').src = postedPhotos[numberOfPicture].url;

**Comment by Morfey216** [comment]
я бы это 
https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L46
переместил сюда
https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L119

**Comment by kirillgenets** [comment]
> используй
> var pictureTemplate = document.querySelector('#picture').content.querySelector('.picture');
> тогда строка
> https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L140
> 
> 
> тебе даст сразу контент. Соответственно - строки
> https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L141-L147
> 
> 
> можно переписать в виде:
> pictureTemplateClone.querySelector('.picture__img').src = postedPhotos[numberOfPicture].url;

document.querySelector('#picture').content.querySelector('.picture'); - по этой строке браузер ничего не находит и в итоге записывается undefined, если честно, я не совсем понял зачем так делать, если можно просто вот так document.querySelector('#picture'); и это никак не помешает тому, чтобы переписать тот самый участок кода вот таким образом pictureTemplateClone.querySelector('.picture__img').src = postedPhotos[numberOfPicture].url;
Сделал так и все работает

**Comment by kirillgenets** [comment]
> я бы это
> https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L46
> 
> 
> переместил сюда
> https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L119
> 
> ... с учетом изменений, естественно

Переместил и закоммитал

**Comment by Morfey216** [comment]
"document.querySelector('#picture').content.querySelector('.picture'); - по этой строке браузер ничего не находит и в итоге записывается undefined..."
Ну как это не находит? А это тогда что?
http://joxi.ru/zANgPEYhvLM9pr

**Comment by kirillgenets** [comment]
Исправил
