### ISSUE TITLE
Неверная работа валидатора хэштегов

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#29]
Думаю, изображение само за себя скажет...
http://joxi.ru/Vm6P8qxT4nLBVA

**Comment by kirillgenets** [comment]
![Screenshot_114](https://user-images.githubusercontent.com/40032777/65064606-7cdb3b00-d989-11e9-9f93-54517a04e196.png)
не совсем понимаю, только что проверил и у меня работает, вот скрин

**Comment by kirillgenets** [comment]
я понял, он считает пробелы

**Comment by kirillgenets** [comment]
исправил добавлением фильтра на длину хештега в функции в getHashTagsArray
