### ISSUE TITLE
"Плоский" if...

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#30]
https://github.com/kirillgenets/kekstagram/blob/5c9f4cdf6e01b5b23d05a07bf370850b5fd4eb2b/js/main.js#L432-L436
Данную структуру правильнее заменить на тернарный оператор, т.к., по сути, выполняется одно и то же действие - установка цвета
`hashTagInput.style.borderColor = inputErrors ? 'red' : '';`
так проще и правильнее. К тому же - в модулях этот прием используется часто

**Comment by kirillgenets** [comment]
исправил и понял, в таких задачах впредь буду использовать тернарный оператор, он действительно уменьшает громоздкость))
