### ISSUE TITLE
Избыточная логическая проверка

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#31]
https://github.com/kirillgenets/kekstagram/blob/5c9f4cdf6e01b5b23d05a07bf370850b5fd4eb2b/js/main.js#L471
Значением поля **errors[key]** и так является **true** или **false**, 
не логично сравнивать, например, _true === true_

**Comment by kirillgenets** [comment]
исправил, я почему-то совсем забыл, что if принимает true или false и зачем-то поставил дополнительное сравнение..
