### ISSUE TITLE
Именование словарей

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#32]
https://github.com/kirillgenets/kekstagram/blob/5c9f4cdf6e01b5b23d05a07bf370850b5fd4eb2b/js/main.js#L453
При таком имени переменной создается впечатление, что мы имеем дело с массивом, а это не так.
Словари именуются по другому принципу:
**"Что переводим"** + ключевое слово **To** + **"Во что переводим"**
Пример: 
var domainZoneToCountry = {
  ru: 'Russia',
  by: 'Belarus'
}

**Comment by kirillgenets** [comment]
исправил и понял. когда искал в гугле информацию про словари, он сказал, что это массив со строчными индексами, а по факту это и есть объект, поэтому я даже не знал, что они особенно именуются. спасибо

**Comment by Morfey216** [comment]
В JS массив - частный случай объекта...
