### ISSUE TITLE
Оптимизация...

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#33]
В этом фрагменте получается любопытная логика: отрабатывает IIFE-функция, которая запускает функцию чтобы та запустила функцию... Зачем эта цепочка?
https://github.com/kirillgenets/kekstagram/blob/64ce01e042f68db1a17f31ad01a19fa93243f42b/js/draw-all-pictures.js#L3-L10

**Comment by Morfey216** [comment]
Второй момент: 
https://github.com/kirillgenets/kekstagram/blob/64ce01e042f68db1a17f31ad01a19fa93243f42b/js/draw-all-pictures.js#L41
+
https://github.com/kirillgenets/kekstagram/blob/64ce01e042f68db1a17f31ad01a19fa93243f42b/js/draw-all-pictures.js#L54-L56
В таком виде можно упростить, т.к. нет смысла создавать функцию, чтобы прочесть атрибут.
`window.drawBigPicture(evt.currentTarget.dataset.number);`

**Comment by kirillgenets** [comment]
Исправил
