### ISSUE TITLE
Отдельный модуль

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#35]
https://github.com/kirillgenets/kekstagram/blob/2924d29d851a9b221fd55b09ad2c4225e82fa3cc/js/filtrate.js#L104-L110
debouns - это самостоятельная утилита, никак не связанная с фильтрами. Необходимо вынести в отдельный модуль.

**Comment by kirillgenets** [comment]
перенёс

**Comment by Morfey216** [comment]
> перенёс

Закоммитил? Не вижу изменений в ветке.

**Comment by kirillgenets** [comment]
уже закоммитил, в колледже интернет мой что-то тупил и отправить не получилось
