### ISSUE TITLE
Неэффективный алгоритм выборки

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#36]
https://github.com/kirillgenets/kekstagram/blob/2924d29d851a9b221fd55b09ad2c4225e82fa3cc/js/filtrate.js#L74-L79
В данном коде непрогнозируемое количество повторений цикла. Необходимо оптимизировать.
https://learn.javascript.ru/array-methods#splice

**Comment by kirillgenets** [comment]
исправил на sort + splice

**Comment by Morfey216** [comment]
Не самое лучшее решение, но ладно, пока оставим...

**Comment by kirillgenets** [comment]
мне тоже нравится))
