### ISSUE TITLE
Ошибка логики работы + избыточность

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#37]
https://github.com/kirillgenets/kekstagram/blob/2924d29d851a9b221fd55b09ad2c4225e82fa3cc/js/filtrate.js#L11-L15
В данном случае принципиально неверный подход. Создание объекта такого рода приводит к двум проблемам:
1. Избыточность данных - ты получаешь и хранишь копии уже имеющейся информации. Что будешь делать, если таких фильтров будет не 3, а 300?
2. Неизменяемость данных. На странице данные могут динамически изменяться: пользователь загрузил изображение, добавил комментарий или поставил лайк. Эти изменения должны учитываться при работе интерфейса.

Нужно реализовать **динамический** механизм получения данных.

**Comment by kirillgenets** [comment]
убрал этот горе-объект и теперь при выборе определенного фильтра меняется сам объект window.data

**Comment by Morfey216** [comment]
А я ведь предупреждал - сохрани исходные данные!
https://gyazo.com/056db2fc0be61d99da1ebc2141e019c8

Ты вообще тестируешь результаты своей работы, или как?

**Comment by kirillgenets** [comment]
понял свои ошибки. во-первых создал переменную defaultData, в которой сохраняется стандартное значение window.data + теперь буду тестировать все возможные случаи, потому что мой код что-то по-разному ведет себя в таких ситуациях, хотя должен одинаково..
