### ISSUE TITLE
Ошибка показа большого изображения

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#39]
Исправить:
https://gyazo.com/4d1cbd2a803e7e5a8c4a86ef3263f2b6

**Comment by kirillgenets** [comment]
исправил. забавно, что исправив один косяк, сам по себе исчезает и другой)

**Comment by Morfey216** [comment]
Что-то снова "пошло не так"...
https://gyazo.com/1421977853d62c54b4d31343cf4535f7

**Comment by kirillgenets** [comment]
исправил, опять невнимательность
