### ISSUE TITLE
Не реализована обработка ошибок при работе с сервером

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#41]
Отсутствует обработка ошибок при работе с сервером.

Адрес изменен умышленно для имитации проблемы. 
Обработки ошибки нет, сообщений об ошибках пользователю тоже нет.

http://joxi.ru/MAj4LYoTj9qlYm

**Comment by kirillgenets** [comment]
добавил обработку события timeout, исправлено

**Comment by Morfey216** [comment]
Не исправлено!
http://joxi.ru/Rmz4JpxTY4WBjA
