### ISSUE TITLE
JSON.parse

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#42]
https://github.com/kirillgenets/kekstagram/blob/2924d29d851a9b221fd55b09ad2c4225e82fa3cc/js/data.js#L7-L8
Парсинг JSON нужно перенести в подобающее ему место. В модуль data должны приходить уже готовые данные.

Дополнено: смотри https://github.com/kirillgenets/kekstagram/issues/43 , я расписал подробнее

**Comment by kirillgenets** [comment]
убрал.
