### ISSUE TITLE
Тип данных в запросе

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#43]
При работе с JSON лучше добавлять такую строку:
`xhr.responseType = 'json';`
сразу после https://github.com/kirillgenets/kekstagram/blob/2924d29d851a9b221fd55b09ad2c4225e82fa3cc/js/backend.js#L11
т.е. применительно к твоему коду получим
```
var dataRequest = new XMLHttpRequest();
dataRequest.responseType = 'json';
```
соответственно `onLoad(dataRequest.responseText);` изменится на `onLoad(dataRequest.response);`

Парсить JSON в таком случае уже не надо...

**Comment by kirillgenets** [comment]
спасибо за объяснение, понял, что выполнял лишние действия и исправил

**Comment by Morfey216** [comment]
Не исправлено!..
https://github.com/kirillgenets/kekstagram/blob/6ed10978c1d20cd04073e58d5085d836cdb3157b/js/backend.js#L30-L38

**Comment by kirillgenets** [comment]
исправил
