### ISSUE TITLE
Дублирование логики

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#46]
Мне очень не нравятся эти повторяющиеся блоки кода. Если у тебя дублируется логика, то обычно ее выносят в функцию.
https://github.com/kirillgenets/kekstagram/blob/6ed10978c1d20cd04073e58d5085d836cdb3157b/js/filtrate.js#L30-L32
https://github.com/kirillgenets/kekstagram/blob/6ed10978c1d20cd04073e58d5085d836cdb3157b/js/filtrate.js#L42-L44
https://github.com/kirillgenets/kekstagram/blob/6ed10978c1d20cd04073e58d5085d836cdb3157b/js/filtrate.js#L55-L57

И вот эти:
https://github.com/kirillgenets/kekstagram/blob/6ed10978c1d20cd04073e58d5085d836cdb3157b/js/filtrate.js#L35-L37
https://github.com/kirillgenets/kekstagram/blob/6ed10978c1d20cd04073e58d5085d836cdb3157b/js/filtrate.js#L47-L50
https://github.com/kirillgenets/kekstagram/blob/6ed10978c1d20cd04073e58d5085d836cdb3157b/js/filtrate.js#L60-L63

Уверен - есть более оптимальное решение!

**Comment by kirillgenets** [comment]
кажется, что нашел наиболее оптимальный вариант. только есть один момент, стоит ли мне проверять, была ли активна кнопка на момент клика? у меня в старом варианте это есть, в новом убрал, потому что выглядит грязно.

**Comment by Morfey216** [comment]
> стоит ли мне проверять, была ли активна кнопка на момент клика?

Учитывая, что данные на странице могут измениться, должна оставаться возможность заново выполнить одну и ту же выборку, поэтому логично кнопки оставить активными

**Comment by kirillgenets** [comment]
теперь я понял, спасибо
