### ISSUE TITLE
Неиспользуемый параметр

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#47]
Что-то не учишься ты на своих ошибках...

https://github.com/kirillgenets/kekstagram/blob/9898b2e3dfd8572b5b7327cd562bd471940e5463/js/filtrate.js#L9
https://github.com/kirillgenets/kekstagram/blob/9898b2e3dfd8572b5b7327cd562bd471940e5463/js/filtrate.js#L38
https://github.com/kirillgenets/kekstagram/blob/9898b2e3dfd8572b5b7327cd562bd471940e5463/js/avoid-debounce.js#L11

**Comment by kirillgenets** [comment]
убрал
