### ISSUE TITLE
Реализация сообщений пользователю

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#48]
Говорил же - перечитай ТЗ...
3.3. При успешной отправке формы, форма редактирования изображения закрывается, все данные, введённые в форму и контрол фильтра, приходят в исходное состояние. Поле загрузки фотографии, стилизованное под букву «О» в логотипе, очищается.
**На экран выводится сообщение об успешной загрузке изображения.**

Сообщения не вижу: https://gyazo.com/265d3571c0cc1ff21153d30ce2a9dfe7

**Comment by kirillgenets** [comment]
добавил сообщение об успешной загрузке

**Comment by Morfey216** [comment]
Не понятно, чем отличается логика работы двух кнопок???
https://gyazo.com/50c0698dea14e1d1c59e68530e4483be
https://gyazo.com/b14c2d3445e9ccce9953ba5ef241a46e

**Comment by kirillgenets** [comment]
исправил этот момент и закоммитил
