### ISSUE TITLE
Комментарии...

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#5]
Что-то мне очень не нравится этот участок кода:
https://github.com/kirillgenets/kekstagram/blob/f29da150f9df0c9aa593bac6212c4ab45c6ec981/js/main.js#L163-L171
1. Работу с разметкой в виде строки надо заменить на явное создание элементов. Например
var newComment = document.createElement('li'); 
Затем прописываешь классы, атрибуты и значения. 
Создай отдельную функцию рендера одного комментария и используй ее, она тебе пригодится не только при открытии большого изображения, но и при добавлении новых комментариев.
2. В задании указано "Сразу после открытия изображения в полноэкранном режиме отображается не более 5 комментариев" - не вижу у тебя проверки условия. Дополнительно рекомендую предусмотреть механизм добавления новых комментариев с условием "не более 5 штук за один раз".

**Comment by Morfey216** [comment]
Первую часть ты сделал, принимается, но с уточнением...
https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L186
Правильнее было бы вернуть созданный комментарий в место вызова функции и выполнять вставку уже там

Второй пункт не реализован.

**Comment by kirillgenets** [comment]
> Первую часть ты сделал, принимается, но с уточнением...
> https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L186
> 
> 
> Правильнее было бы вернуть созданный комментарий в место вызова функции и выполнять вставку уже там
> Второй пункт не реализован.
> Смотрим по порядку код:
> https://github.com/kirillgenets/kekstagram/blob/9653ddc50c9ed0c5e690f27bbf18e1ee497dcfe2/js/main.js#L192-L198
> 
> Ты проходишь в цикле все комментарии от 0 до postedPhotos[numberOfPicture].comments.length
> и внутри проверяешь на условие "если меньше 5 - добавляем"...
> А для чего делать перебор остальных комментариев? Их ведь может быть и 5, и 20, и 138 ))
> 
> Далее - не предусмотрен механизм добавления новой пятерки комментариев к уже показанным...
> 
> Рекомендации: объяви константу количества комментариев (5 штук), при добавлении комментариев определяй номер начального и номер конечного добавляемого комментария, учти условие выхода за пределы общего количества комментариев. А затем уже запусти цикл добавления

насчет механизма добавления новых комментариев: мне нужно сделать так, чтобы при добавлении новой пятерки комментариев, проверялось, сколько старых комментариев уже показано, чтобы знать, сколько старых нужно скрыть, чтобы показать новые? Ну, типа, есть уже 4 комментария и подошло 4 новых, значит последний комментарий старый остается и к нему добавляются 4 новых, да?

**Comment by Morfey216** [comment]
нет, так не пойдет:
https://github.com/kirillgenets/kekstagram/blob/a918c4934e632a4fb8d4b3b02a24c38ee73a7bf2/js/main.js#L188-L194

"насчет механизма добавления новых комментариев:...."
При открытии изображения сразу показывается не более 5 комментариев, а затем по клику к ним просто добавляются новые, тоже не более 5 за один раз. Старые никуда не исчезают.

**Comment by kirillgenets** [comment]
Изменил цикл на while с адекватным условием, но пока не продумал механизм добавления новых комментариев

**Comment by Morfey216** [comment]
ОК, давай тогда это оставим "на потом", позже будет задание...
А пока надо доделать вот что: думаю, этот код
https://github.com/kirillgenets/kekstagram/blob/d59b7eb366337d8625f10321165dd06f8d87ecce/js/main.js#L53
следует также переместить в подобающее ему место:
https://github.com/kirillgenets/kekstagram/blob/d59b7eb366337d8625f10321165dd06f8d87ecce/js/main.js#L149-L151
Т.к. блок комментариев находится внутри, то и находить его нужно внутри

**Comment by kirillgenets** [comment]
Переместил объявление переменной + предусмотрел добавление новых комментариев к уже показанным

**Comment by Morfey216** [comment]
https://github.com/kirillgenets/kekstagram/blob/9a6dd5e26535ce39c2fdf027a5b4b2e9f01c0a22/js/main.js#L10
Этой переменной не место в общей области видимости

**Comment by Morfey216** [comment]
https://github.com/kirillgenets/kekstagram/blob/9a6dd5e26535ce39c2fdf027a5b4b2e9f01c0a22/js/main.js#L191

Рекомендуют при множественных добавлениях в DOM создать DocumentFragment, добавить в него все необходимые узлы и лишь затем добавить фрагмент в DOM-дерево

**Comment by kirillgenets** [comment]
исправил
