### ISSUE TITLE
Именование функции

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#6]
Всё-таки не нравится мне это название
https://github.com/kirillgenets/kekstagram/blob/d59b7eb366337d8625f10321165dd06f8d87ecce/js/main.js#L137

Функция у тебя создает не просто DOM-элемент, а некую весьма конкретную структуру, так почему бы не дать ей соответствующее название?

**Comment by kirillgenets** [comment]
Изменил и закоммитал

**Comment by Morfey216** [comment]
Можно было просто createPicture...

**Comment by kirillgenets** [comment]
исправил
