### ISSUE TITLE
Некорректная работа фильтров

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#7]
http://joxi.ru/ZrJlP8YTwOxjW2

При повторной загрузке изображения остается старый фильтр.
Пересмотри работу функции https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L424

**Comment by kirillgenets** [comment]
исправил, т.е. в функции hideImageEditor вызывается функция useFilter('none'); Правильно ли такое решение?

**Comment by Morfey216** [comment]
Нет, не правильно. Это логически не имеет смысла - зачем менять фильтр для закрывающегося изображения?

**Comment by kirillgenets** [comment]
сделал, все работает
