### ISSUE TITLE
Дублирование поиска по DOM-дереву

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#8]
Вроде как обсуждали уже неоднократно...
Множественные нарушения.
1. https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L330
и здесь:
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L380
причем этот элемент находится в области видимости функции hideBigPicture()...
2.
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L335
и
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L342
3. Та же проблема, что и в 1-м пункте:
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L398
https://github.com/kirillgenets/kekstagram/blob/ce85228f9049b526ac89caa43373f3c0a72584f5/js/main.js#L426

Пройтись по всему коду и исправить...

**Comment by kirillgenets** [comment]
исправил
