### ISSUE TITLE
Дублирование вызова функции

### ISSUE THREAD

**Issue by Morfey216** [kirillgenets/kekstagram#9]
http://joxi.ru/8AneRLoFzaM5Z2

В результате получаешь такие проблемы:
http://joxi.ru/krDXYZlUKkVQvr

**Comment by kirillgenets** [comment]
исправил

**Comment by Morfey216** [comment]
ну-ну...
Правильно ли я понимаю, что при КЛИКЕ по крестику обработчик НАЖАТИЯ КЛАВИШ не удаляется? И наоборот тоже самое - при закрытии кейдауном не удаляется обработчик клика???
Вот код...
https://github.com/kirillgenets/kekstagram/blob/8675db28448da4bd0d5083c247167e6bcb7c63be/js/main.js#L407-L422

**Comment by kirillgenets** [comment]
исправил это + добавил ремувер для события фокуса на фильтрах
